### PR TITLE
Feat/cpe 6896 shaka upgrade

### PR DESCRIPTION
**Pull request by vishnump-discovery**
## Description

We need to upgrade the shaka player to 3.2.4 version. 

The tracking ticket can be found from - https://discoveryinc.atlassian.net/browse/CPE-6896

I have followed the below steps

1. Created the feature branch from "Discovery_Shaka_Feature_Branch"
2. Merged the release tag V3.2.4 from google shaka
3. Build the packages
4. Published the version 3.2.4-custom to public npm.

Now the latest shaka player can be found from - https://cdn.jsdelivr.net/npm/@discovery-dni/shaka-player@3.2.4-custom/dist/shaka-player.compiled.debug.js

## Type of change

[CPE-6783](https://discoveryinc.atlassian.net/browse/CPE-6783)
[CPE-6784](https://discoveryinc.atlassian.net/browse/CPE-6784)

### CODE REVIEW

**Review by ravi-movva — CHANGES_REQUESTED** [review]
We are not supposed to see all these files.
1)  You should rebase our feature branch against 3.2.4 
2) then we we will be able to see only the changes that Arek did

**Review by awojtasd — COMMENTED** [review]
Can we please first push vanilla 3.2.4 and then on top of 3.2.4 create a commit with our commits? It will be much easier to review.

**Comment by vishnump-discovery** [comment]
I will try the rebase scenario also initially I did that way only but was not working because our master branch having the release tag version upto 3.2.0. So we need to take the latest tag pull also.

**Comment by ravi-movva** [comment]
it is taken care by another PR

**Pull request closed without merging**
